---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - k3s
    - flux-cd
  loop_control:
    loop_var: role

- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        timeout: 30
      any_errors_fatal: true

    - name: Install Flux CLI
      ansible.builtin.shell:
        cmd: curl -s https://fluxcd.io/install.sh | bash
      environment:
        FLUX_VERSION: '{{ fluxcd_vars.release.version }}'
      register: fluxcd_result
      changed_when: "'flux' in fluxcd_result.stdout"
      run_once: true

    - name: Bootstrap Flux
      ansible.builtin.command:
        cmd: >-
          flux bootstrap github
          --owner={{ global_map.credentials.fluxcd.github.owner }}
          --repository={{ global_map.credentials.fluxcd.github.repository }}
          --branch={{ fluxcd_vars.git.branch }}
          --path={{ fluxcd_vars.git.path }}
          --namespace={{ fluxcd_vars.kubernetes.namespace }}
          --personal={{ fluxcd_vars.github.personal | lower }}
      environment:
        GITHUB_TOKEN: '{{ global_map.credentials.fluxcd.github.token }}'
        KUBECONFIG: '{{ k3s_project.cluster.kubeconfig }}'
      register: fluxcd_result
      run_once: true
      changed_when: true
      no_log: true
