{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "terminus.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terminus.labels" . | nindent 4 }}
  {{- if .Values.gateway.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.gateway.clusterIssuer }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      {{- if not .Values.gateway.http.direct }}
      hostname: {{ .Values.gateway.hostname | quote }}
      {{- end }}
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.gateway.tls.enabled }}
    - name: https
      hostname: {{ .Values.gateway.hostname | quote }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ include "terminus.name" . }}-tls
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
{{- end }}
