apiVersion: v1
kind: Service
metadata:
  name: {{ include "terminus.name" . }}-valkey
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terminus.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "terminus.valkey.selectorLabels" . | nindent 4 }}
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
