apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/terminus
  - secret.sops.yaml
patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: terminus
        namespace: flux-system
      spec:
        values:
          app:
            timezone: "America/New_York"
            apiUri: "https://terminus.noty.cc"
            rackAttackAllowedSubnets: "10.42.0.0/16"
          cnpg:
            instances: 1
            database: terminus
            owner: terminus
            storage:
              size: 5Gi
          persistence:
            storageClass: longhorn
            size: 2Gi
          gateway:
            enabled: true
            hostname: terminus.noty.cc
            tls:
              enabled: false
            http:
              direct: true
