# Encrypt before committing:
#   sops --encrypt --in-place apps/production/terminus/secret.sops.yaml
#
# Generate APP_SECRET with: openssl rand -hex 32
apiVersion: v1
kind: Secret
metadata:
    name: terminus-secrets
    namespace: terminus
type: Opaque
stringData:
    APP_SECRET: ENC[AES256_GCM,data:HxabEC+SzRF3XJltjIJOPq7CKSwVfN1gwDP4WbKJ2vtVXCKyOl0l5iyhWRdKEUpD+ux+mRt1zaqZbFkDyunxaA==,iv:73krgCTmgRZbSSOVh/7fDdjhdZmOgM96GTBNFVVkNik=,tag:cwygk6Hs4BRLXH39sr5Ohg==,type:str]
sops:
    age:
        - recipient: age1nktvza935ny7k74ucsczdeps40qnuy0tt8znd2fu8ztz29xr6vpq2gppna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L2pOTkIvY0EyTEt5Q08y
            MEU5d0JrZzlxMjlBTTVMNTlKV2JMcHhCQXhzCkwyRGtLejdTeHUyMXN0b3IyYTFv
            bk8xWFFqZUlyWXhSKzR3Z1pSOWh5MFUKLS0tIG9UNURDQWhuVXZ1MmVZcEdoSE9u
            Y0FPUDZYQzRPS2FBemNRckVKS0tuT1EKj5noEKT7XrCekzxGhUVal1+KGBtdQTdx
            iUv9kumWMmaxtsh4nOdV/E4TuejbozUpdHq9O/lX6OKrSRRbtkv45A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T03:15:47Z"
    mac: ENC[AES256_GCM,data:TGsXx8iT+1b+MsWxALOy23ViQdnhxSm9YeQRE0I11b7PoLWkGJ4xO/3MtqULDN1wmms9pZR3eSzoqXDL7UzCkSSJ8QXOPj6VkpkjX/s3YjqM60L2Y6nYPVPzoL7Om3yAU4b3AavVQH7DPs/yfUsH/r2AIA6it7dDfFA1b+eY490=,iv:mOwSw7oSquv1DpX0gEQSW4aa88s0TrjXV4xdQ8Z4PA0=,tag:svE83/9xC/jO+fREECiPow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
