apiVersion: v1
kind: Secret
metadata:
    name: terminus-secrets
    namespace: terminus
type: Opaque
stringData:
    APP_SECRET: ENC[AES256_GCM,data:sm4/T7ouOEerE9mS3kiWK+YtBGGskmyZclR8eKTQIBsR8ZWUZnYxPPKVIS2WqsXWHy/inYyr0Yb2pWkIzUCODg==,iv:Dhi/coixudZbAeYGf/0DYrw1FIi5nZ3YO8ij/jPCwK4=,tag:TcxqLM2BibQbT1ft1MMXjg==,type:str]
sops:
    age:
        - recipient: age18nq3nxxlpp68r9egs8637gm075w3nqetrtsu79w409f2n59fnfjse6gg8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV1VjdnRtazdZU3RBbENS
            VDZNekxhbm1vTVY5ZWt2bWI4bm80WXcxY3pvCm96VkhKQmU1VGJXWXdIZEIzNTg0
            UnNpVVkvWDJVTjlDaUZ2MmthZUl2TVEKLS0tIFBHK2VJbnJyZnpMaTJma0E1aHJJ
            SXg0aUZOc3I0YWFRdW54Z2Z0S2Nmb00Kka8UY8r25ccXAG0KrhoL4XLUAEK1uXan
            iuWfLB8cDJ187nd9gR2tMeexpwNefanCFgRYEQXvO8uVTB0etVmfow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T03:39:11Z"
    mac: ENC[AES256_GCM,data:y34gmGx0gZziWy+Nsnjd3Sh4MVgHoay2AEpz3IrLcWjB9G7BSkKiKObr1drgoLxoTNHUFD43Z9emT6D4EC9pAAPcIq6LmLFOpBdmHbfzDRMRtV7x2SoAL0MKTuYkene0OzzZ6b1wKeSlSRHaJPCeNgYS1AbN/O70Kovoiu4R4A4=,iv:CobhR5pxeMLD4TMVuU8aGDJIAynQ3LHxF+/K+JAfMhY=,tag:dsKsGbz9LJ+6K2+WWT64Kw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
