---
fluxcd_vars:
  kubernetes:
    namespace: flux-system
  git:
    branch: master
    path: clusters/production
  github:
    # -- Set to true for personal repositories, false for organization repositories
    personal: true
  release:
    version: 2.8.5
