---
fluxcd_vars:
  kubernetes:
    namespace: flux-system
  git:
    branch: master
    path: clusters/production
  github:
    # -- Set to true for personal repositories, false for organization repositories
    personal: true
  release:
    version: 2.8.5
  sops:
    # -- age private key is written here during provisioning then stored as a K8s secret
    key_path: /tmp/flux-sops-age.agekey
    secret_name: sops-age
